import streamlit as st
import pandas as pd
import time
import os

# -----------------------------
# CONFIGURATION
# -----------------------------
LOG_FILE = "../data/log.csv"  # path to CSV generated by pipeline.py
UPDATE_INTERVAL = 1  # seconds

# -----------------------------
# STREAMLIT APP
# -----------------------------
st.set_page_config(page_title="Retail Analytics Dashboard", layout="wide")
st.title("Retail Analytics Dashboard")
st.subheader("Live people counting and occupancy tracking")

# Check if CSV exists
if not os.path.exists(LOG_FILE):
    st.warning("Log file not found. Run pipeline.py first!")
    st.stop()

# Placeholder containers for live updates
occupancy_chart = st.empty()
in_out_chart = st.empty()
summary_stats = st.empty()

# -----------------------------
# MAIN LOOP
# -----------------------------
while True:
    try:
        # Read log CSV
        df = pd.read_csv(LOG_FILE, parse_dates=["timestamp"])
